apiVersion: v1
kind: Service
metadata:
  name: yolo-app
spec:
  selector:
    app: yolo_app
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yolo_app
  template:
    metadata:
      labels:
        app: yolo_app
    spec:
      containers:
        - name: app
          image: backend
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/yolomy
          imagePullPolicy: Always