version: "3.8"

services:
    client:
        image: client
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - /client/node_modules
        networks:
            webappnetwork   

    backend:
            image: server
            restart: always
            ports:
            - "8080:8080"
            volumes:
            - /backend/node_modules
            depends_on:
            - mongodb
            networks:
             webappnetwork

    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth --smallfiles
        networks:
            - webappnetwork     
                
    networks:
            webappnetwork:
                 driver: bridge         