apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yolo_app
  template:
    metadata:
      labels:
        app: yolo_app
    spec:
      containers:
        - name: app
          image: client
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/yolomy
          imagePullPolicy: Always